// <auto-generated />
using System;
using DuAnCuaToi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuAnCuaToi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260912102830_AddDaDiemDanhToLichTap")]
    partial class AddDaDiemDanhToLichTap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuAnCuaToi.Models.ChiSoSucKhoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CanNang")
                        .HasColumnType("float");

                    b.Property<double>("ChieuCao")
                        .HasColumnType("float");

                    b.Property<int>("HoiVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoiVienId");

                    b.ToTable("ChiSoSucKhoes");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.GoiTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiNhanhId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsKhuyenMai")
                        .HasColumnType("bit");

                    b.Property<string>("MaGoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiHanNgay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GoiTaps");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.GoiTapDichVu", b =>
                {
                    b.Property<int>("GoiTapId")
                        .HasColumnType("int");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.HasKey("GoiTapId", "DichVuId");

                    b.HasIndex("DichVuId");

                    b.ToTable("GoiTapDichVus");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.HoiVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucTieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGianRanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiGoi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HoiViens");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.LichTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDiemDanh")
                        .HasColumnType("bit");

                    b.Property<int>("HoiVienId")
                        .HasColumnType("int");

                    b.Property<string>("KhungGio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaPT")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PTUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HoiVienId");

                    b.HasIndex("MaPT");

                    b.ToTable("LichTaps");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CanNang")
                        .HasColumnType("float");

                    b.Property<double>("ChieuCao")
                        .HasColumnType("float");

                    b.Property<string>("GhiChuSucKhoe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucTieuTapLuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PTPhuTrach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.PhieuDangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoiTapId")
                        .HasColumnType("int");

                    b.Property<int>("HoiVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoiTapId");

                    b.HasIndex("HoiVienId");

                    b.ToTable("PhieuDangKys");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.ChiSoSucKhoe", b =>
                {
                    b.HasOne("DuAnCuaToi.Models.NguoiDung", "HoiVien")
                        .WithMany()
                        .HasForeignKey("HoiVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoiVien");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.GoiTapDichVu", b =>
                {
                    b.HasOne("DuAnCuaToi.Models.DichVu", "DichVu")
                        .WithMany("GoiTapDichVus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuAnCuaToi.Models.GoiTap", "GoiTap")
                        .WithMany("GoiTapDichVus")
                        .HasForeignKey("GoiTapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("GoiTap");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.LichTap", b =>
                {
                    b.HasOne("DuAnCuaToi.Models.NguoiDung", "HoiVien")
                        .WithMany()
                        .HasForeignKey("HoiVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuAnCuaToi.Models.NguoiDung", "PT")
                        .WithMany()
                        .HasForeignKey("MaPT");

                    b.Navigation("HoiVien");

                    b.Navigation("PT");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.PhieuDangKy", b =>
                {
                    b.HasOne("DuAnCuaToi.Models.GoiTap", "GoiTap")
                        .WithMany("PhieuDangKys")
                        .HasForeignKey("GoiTapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DuAnCuaToi.Models.HoiVien", "HoiVien")
                        .WithMany()
                        .HasForeignKey("HoiVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiTap");

                    b.Navigation("HoiVien");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.DichVu", b =>
                {
                    b.Navigation("GoiTapDichVus");
                });

            modelBuilder.Entity("DuAnCuaToi.Models.GoiTap", b =>
                {
                    b.Navigation("GoiTapDichVus");

                    b.Navigation("PhieuDangKys");
                });
#pragma warning restore 612, 618
        }
    }
}
